def get_keywords():
	return ['african_american','Armenian','Persian','American',
'Filipino','English','Norwegian','Dutch','Israeli','Nigerian', 'Ethiopia', 
'Europe', 'European', 'Russian', 'Ukraine',
'Sudan', 'Afghanistan' ,'Iraq', 'Yemen', 'Ukrainian', 'Russia',
'Italy', 'Somali', 'Iran', 'Afghan', 'Indian', 'Italian',
'Australian', 'Spanish', 'Guatemalan', 'Hispanic', 'Venezuela', 'Sudanese',
'Oman', 'Finnish', 'Swedish', 'Venezuelan', 'Puerto_Rican', 'Ghanaian',
'Moroccan', 'Somalia', 'Saudi_Arabian', 'Syria', 'Chinese', 'Pakistani',
'China', 'India', 'Irish', 'Britain', 'France', 'Greece',
'Scotland', 'Mexican', 'Paraguayan', 'Brazil', 'African', 'Eritrean',
'Sierra_Leonean', 'Africa', 'Jordan', 'Indonesia', 'Vietnam', 'Pakistan',
'German', 'Romania' ,'Brazilian', 'Ecuadorian', 'Mexico', 'Puerto_Rico',
'Kenyan', 'Liberian', 'Cameroonian', 'African_Americans', 'Kenya', 'Liberia',
'Sierra_Leon', 'Qatari', 'Syrian', 'Arab', 'Saudi_Arabia', 'Lebanon',
'Indonesian', 'French', 'Norwegian', 'South_Africa', 'Jordanian', 'Korea'
,'Singapore', 'Romanian', 'Crimean', 'Native_American', 'Germany', 'Ireland',
'Ecuador', 'Morocco', 'Omani', 'Iranian', 'Iraqi', 'Qatar',
'Turkey', 'Vietnamese', 'Nepali', 'Laos', 'Bangladesh', 'British',
'Polish', 'Greek', 'Scottish', 'Bolivian', 'Guatemala', 'Ghana',
'Cameroon', 'Japanese', 'Taiwanese','Bengali', 'Nepal', 'Albanian',
'Albania', 'Columbian', 'Peruvian', 'Argentian', 'Spain', 'Paraguay',
'Ethiopian', 'Egyptian', 'Persian_people', 'Sweden', 'Crimea', 'Portuguese',
'Argentina', 'Chile', 'Cape_Verdean', 'Turkish', 'Yemeni', 'Taiwan',
'Austrian', 'White_people', 'Finland', 'Australia', 'South_African', 'Eriteria',
'Egypt', 'Korean', 'Dutch_people', 'Peru', 'Poland', 'Chilean',
'Columbia', 'Bolivia', 'Laotian', 'Lebanese', 'Japan', 'Norway',
'Cape_Verde', 'Portugal', 'Austria', 'Singaporean', 'Netherlands','she',
'he','hers','him','her','herself', 'himself', 'his','woman','man','female',
'male','lady','gentleman','ladies','gentlemen','girl','boy' ,'sir', 'ma_am',
'mother','father','stepmother','stepfather','daughter', 'son','sister', 
'brother',  'grandmother',   'grandfather' ,
'mommy', 'daddy','wife','husband','bride', 'groom','girlfriend', 'boyfriend',
'schoolgirl' , 'schoolboy','Sharia', 'Jihad', 'Christian', 'Muslim', 'Islam', 'Hindu',
'Mohammed', 'church',  'Quran','Bible','Brahmin','Holy_Trinity','barber', 'coach', 
'businessperson', 'football_player', 'construction_worker', 'manager',
'CEO', 'accountant', 'commander', 'firefighter', 'mover', 'software_developer',
'guard', 'baker', 'doctor', 'athlete', 'artist', 'dancer',
'mathematician', 'janitor', 'carpenter', 'mechanic', 'actor', 'handyman',
'musician', 'detective', 'politician', 'entrepreneur', 'model', 'opera_singer',
'chief', 'lawyer', 'farmer', 'writer', 'librarian', 'army',
'real_estate_developer', 'broker', 'scientist', 'butcher', 'electrician', 'prosecutor',
'banker', 'cook', 'hairdresser', 'prisoner', 'plumber', 'attorney',
'boxer', 'chess_player', 'priest', 'swimmer', 'tennis_player', 'supervisor',
'attendant', 'housekeeper', 'maid', 'producer', 'researcher', 'midwife',
'judge', 'umpire', 'bartender', 'economist', 'physicist', 'psychologist',
'theologian', 'salesperson', 'physician', 'sheriff', 'cashier', 'assistant',
'receptionist', 'editor', 'engineer', 'comedian', 'painter', 'civil_servant',
'diplomat', 'guitarist', 'linguist', 'poet', 'laborer', 'teacher',
'delivery_man', 'realtor', 'pilot', 'professor', 'chemist', 'historian',
'pensioner', 'performing_artist', 'singer', 'secretary', 'auditor', 'counselor',
'designer', 'soldier', 'journalist', 'dentist', 'analyst', 'nurse',
'tailor', 'waiter', 'author', 'architect', 'academic', 'director',
'illustrator', 'clerk', 'policeman', 'chef', 'photographer', 'drawer',
'cleaner', 'pharmacist', 'pianist', 'composer', 'handball_player', 'sociologist']


def get_country_keywords():
	return ['african_american','Armenian','Persian','American','Filipino','English','Norwegian','Dutch','Israeli','Nigerian', 'Ethiopia', 'Europe', 'European', 'Russian', 'Ukraine',
'Sudan', 'Afghanistan' ,'Iraq', 'Yemen', 'Ukrainian', 'Russia',
'Italy', 'Somali', 'Iran', 'Afghan', 'Indian', 'Italian',
'Australian', 'Spanish', 'Guatemalan', 'Hispanic', 'Venezuela', 'Sudanese',
'Oman', 'Finnish', 'Swedish', 'Venezuelan', 'Puerto_Rican', 'Ghanaian',
'Moroccan', 'Somalia', 'Saudi_Arabian', 'Syria', 'Chinese', 'Pakistani',
'China', 'India', 'Irish', 'Britain', 'France', 'Greece',
'Scotland', 'Mexican', 'Paraguayan', 'Brazil', 'African', 'Eritrean',
'Sierra_Leonean', 'Africa', 'Jordan', 'Indonesia', 'Vietnam', 'Pakistan',
'German', 'Romania' ,'Brazilian', 'Ecuadorian', 'Mexico', 'Puerto_Rico',
'Kenyan', 'Liberian', 'Cameroonian', 'African_Americans', 'Kenya', 'Liberia',
'Sierra_Leon', 'Qatari', 'Syrian', 'Arab', 'Saudi_Arabia', 'Lebanon',
'Indonesian', 'French', 'Norwegian', 'South_Africa', 'Jordanian', 'Korea'
,'Singapore', 'Romanian', 'Crimean', 'Native_American', 'Germany', 'Ireland',
'Ecuador', 'Morocco', 'Omani', 'Iranian', 'Iraqi', 'Qatar',
'Turkey', 'Vietnamese', 'Nepali', 'Laos', 'Bangladesh', 'British',
'Polish', 'Greek', 'Scottish', 'Bolivian', 'Guatemala', 'Ghana',
'Cameroon', 'Japanese', 'Taiwanese','Bengali', 'Nepal', 'Albanian',
'Albania', 'Columbian', 'Peruvian', 'Argentian', 'Spain', 'Paraguay',
'Ethiopian', 'Egyptian', 'Persian_people', 'Sweden', 'Crimea', 'Portuguese',
'Argentina', 'Chile', 'Cape_Verdean', 'Turkish', 'Yemeni', 'Taiwan',
'Austrian', 'White_people', 'Finland', 'Australia', 'South_African', 'Eriteria',
'Egypt', 'Korean', 'Dutch_people', 'Peru', 'Poland', 'Chilean',
'Columbia', 'Bolivia', 'Laotian', 'Lebanese', 'Japan', 'Norway',
'Cape_Verde', 'Portugal', 'Austria', 'Singaporean', 'Netherlands']

def get_relig_keywords():
	return ['Sharia', 'Jihad', 'Christian', 'Muslim', 'Islam', 'Hindu',
'Mohammed', 'church',  'Quran','Bible','Brahmin','Holy_Trinity']

def get_gender_keywords():
	return ['she','he','hers','him','her','herself', 'himself', 'his','woman','man','female','male','lady','gentleman','ladies','gentlemen','girl','boy' ,'sir', 'ma_am','mother','father','stepmother','stepfather','daughter', 'son','sister', 'brother',  'grandmother',   'grandfather' ,
  'mommy', 'daddy','wife','husband','bride', 'groom','girlfriend', 'boyfriend','schoolgirl' , 'schoolboy']

def get_profession_keywords():
	return ['barber', 'coach', 'businessperson', 'football_player', 'construction_worker', 'manager',
'CEO', 'accountant', 'commander', 'firefighter', 'mover', 'software_developer',
'guard', 'baker', 'doctor', 'athlete', 'artist', 'dancer',
'mathematician', 'janitor', 'carpenter', 'mechanic', 'actor', 'handyman',
'musician', 'detective', 'politician', 'entrepreneur', 'model', 'opera_singer',
'chief', 'lawyer', 'farmer', 'writer', 'librarian', 'army',
'real_estate_developer', 'broker', 'scientist', 'butcher', 'electrician', 'prosecutor',
'banker', 'cook', 'hairdresser', 'prisoner', 'plumber', 'attorney',
'boxer', 'chess_player', 'priest', 'swimmer', 'tennis_player', 'supervisor',
'attendant', 'housekeeper', 'maid', 'producer', 'researcher', 'midwife',
'judge', 'umpire', 'bartender', 'economist', 'physicist', 'psychologist',
'theologian', 'salesperson', 'physician', 'sheriff', 'cashier', 'assistant',
'receptionist', 'editor', 'engineer', 'comedian', 'painter', 'civil_servant',
'diplomat', 'guitarist', 'linguist', 'poet', 'laborer', 'teacher',
'delivery_man', 'realtor', 'pilot', 'professor', 'chemist', 'historian',
'pensioner', 'performing_artist', 'singer', 'secretary', 'auditor', 'counselor',
'designer', 'soldier', 'journalist', 'dentist', 'analyst', 'nurse',
'tailor', 'waiter', 'author', 'architect', 'academic', 'director',
'illustrator', 'clerk', 'policeman', 'chef', 'photographer', 'drawer',
'cleaner', 'pharmacist', 'pianist', 'composer', 'handball_player', 'sociologist']


